name: Email YouTube popular videos

on:
  pull_request:
    branches:
      - main

jobs:
  email-results:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      YOUTUBE_USERNAME: ${{ secrets.YOUTUBE_USERNAME }}}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync

      - name: Run main.py
        run: uv run python ./main.py
